In [ ]:
# 2021/10/4 녹화강의 Numpy조작

In [1]:
import numpy as np

In [2]:
"""
np.arrange(start, stop*, step) : 특정 범위의 정수 배열
Numpy Array Attributes
"""
print(np.arange(3)) # stop
print(np.arange(2, 5)) # start, stop
print(np.arange(1, 9, 2)) # start, stop, step

[0 1 2]
[2 3 4]
[1 3 5 7]


In [31]:
"""
np.random.seed(num) : 똑같은 난수 배열 (재생산성)
np.random.randint(high, size) : 정수로 구성된 난수 배열
Random number generator
"""
arr1 = np.random.randint(10, size = (5)) # 0~9
print(arr1)

arr2 = np.random.randint(100, size = (3, 5)) #행, 열
print(arr2)

arr3 = np.random.randint(100, size = (3, 5, 2)) #문단 행 열
print(arr3)

[3 2 5 7 3]
[[23 19  0 17 50]
 [93 93 66  9 94]
 [54 16 57 85  0]]
[[[12 70]
  [55  1]
  [93 58]
  [43 90]
  [99 30]]

 [[89 45]
  [ 4 22]
  [31 17]
  [20 50]
  [30 17]]

 [[27 18]
  [31 18]
  [51 36]
  [51 57]
  [32 79]]]


In [40]:
# Attributes

print("arr1.ndim = ", arr1.ndim) # 차원 개수
print("arr2.shape = ", arr2.shape) # 배열 차원 크기
print("arr2.size = ", arr2.size) # 전체배열크기
print("arr2.dtype = ", arr2.dtype) # 배열 데이터 타입
print("arr2.itemsize = ", arr2.itemsize) # 배열 원소 별 메모리 크기
# 정수 1개의 값은 4byte
arr4 = np.array([1.5, 2.3, 3.4]) #float
print("arr4.itemsize", arr4.itemsize)
print("arr2.nbyte = ", arr2.nbytes) # 전체 배열 메모리 크기

arr1.ndim =  1
arr2.shape =  (3, 5)
arr2.size =  15
arr2.dtype =  int32
arr2.itemsize =  4
arr4.itemsize 8
arr2.nbyte =  60


In [ ]:
"""
arr[start:stop:step] - 1차원
stop는 포함되지 않음 즉, 미만이라는 뜻
arr[start1:stop1:step1, start2:stop2:step2] - 2차원
"""


In [53]:
"""
Subarrays as no-copy views
list는 복사본을 보여주지만, 배열은 뷰를 보여줌
"""
np.random.seed(1)
arr = np.random.randint(10, size=(3,4))
print(arr, '\n')

arr_sub = arr[:2, :2]
print(arr_sub, '\n')

arr_sub[0, 0] = -1
print(arr_sub, '\n')

print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]] 

[[-1  8  9  5]
 [ 0  0  1  7]
 [ 6  9  2  4]]


In [56]:
# .copy()를 사용하면 복사본을 생성하여 값을 마음대로 바꿀 수 있다.
np.random.seed(1)
arr = np.random.randint(10, size=(3,4))
print(arr)

arr_sub = arr[:2, :2].copy()
print(arr_sub, '\n')

arr_sub[0, 0] = -1
print(arr_sub)

print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]]
[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]


In [57]:
"""
Reshaping of Arrays
배열을 재구조
"""

arr= np.arange(1, 10)
print(arr)

grid = arr.reshape(3, 3)
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
#np.newaxis
arr= np.array([1, 2, 3])
print(arr)
print("arr.ndim =", arr.ndim)
print("arr.shape =", arr.shape)

arr_new = arr[np.newaxis, :]
print(arr_new)
print("arr_new.ndim=", arr_new.ndim)
print("arr_new.shape=", arr_new.shape)

[1 2 3]
arr.ndim = 1
arr.shape = (3,)
[[1 2 3]]
arr_new.ndim= 2
arr_new.shape= (1, 3)


In [68]:
"""
Array concatenation
배열의 연결
"""
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.array([7, 8, 9])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
"""
Array splitting
"""

arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

arr1, arr2, arr3 = np.split(arr, [3, 5])
print(arr1, arr2, arr3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99] [3 2 1]
