In [1]:
#9월29일 연습 202037002신재은

In [8]:
pip install numpy

In [10]:
import numpy as np
import pandas as pd

In [13]:
#creating a Numpy Array
my_list = [1, 2, 3, 4, 5, 6]

my_array = np.array(my_list) #np.array로 변환
print(my_array)

my_array = np.array([1, 2, 3, 4, 5, 6])

[1 2 3 4 5 6]


In [14]:
# .dtype attribute
a = np.array([1, "A", True])
print(a.dtype)

b = np.array([1, 2, 3])
print(b.dtype)

c = np.array([1.1, 2.3])
print(c.dtype)

<U11
int32
float64


In [17]:
"""
Size Comparison od ndarray and list objects
"""

from sys import getsizeof

lst = [1, 2, 3, 4, 5]
print(getsizeof(list)) #차지하고 있는 메모리 공간

arr= np.array([1, 2, 3, 4, 5])
print(getsizeof(arr))

416
116


In [39]:
"""
Operation with Test Scores
"""

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grage)

final_grade = total_grade / 3
print(final_grade)

jeremy_text_1 = test_2[3]
print(jeremy_text_1)

manual_adwoa_test_1 = test_1[1], test_1[2]
print(manual_adwoa_test_1)

student_scores = np.array([test_1, test_2, test_3])
print(student_scores)

print(student_scores[2][0])

print(student_scores[:, 4])

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
(94, 88)
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [46]:
#masking
lst = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = lst > 5
print(mask)

#select using logical operations '&'=논리 곱,'|'= 논리합
selected = lst[(lst > 5) & (lst < 8)]
print(selected)

#combined logical operations

[False False False False False  True  True  True  True  True]
[6 7]
