In [ ]:
#2021-10-6 202037002신재은

In [2]:
import numpy as np

In [11]:
"""
Computing reciprocals in loops
"""

#function for computing reciprocols using looping
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

np.random.seed(0)
values = np.random.randint(1, 10, size=5)
print(values)

output = compute_reciprocals(values)
print(output)

[6 1 4 4 8]
[0.16666667 1.         0.25       0.25       0.125     ]


In [13]:
"""
Comparison : Loop vs ufunsc(vectorized)
"""

big_array = np.random.randint(1, 100, size=100000)
print(big_array)

#Looping on a big array

#magic fuction (%timeit)
%timeit compute_reciprocals(big_array)

[97  2 42 ... 82 73 80]
217 ms ± 9.83 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
#vectorized operations

%timeit 1 / big_array

121 µs ± 1.22 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [24]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)
print(arr1, arr2)

arr1 = arr1 - 2
print(arr1)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

print(arr4 ** 2)


[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]
[ 4 16 25  4 16]
[ 4 16 49 49 81]
[ 1 49  0 36 81]


In [30]:
"""
ufunc : Array artithmetic
"""

#Basic artithmetic operations on array

x = np.arange(4)
print(x)
print(" x + 5 =", x + 5)
print(" x - 5 =", x - 5)
print(" x * 2 =", x * 2)
print(" x / 2 =", x / 2)
print(" x ** 2 =", x ** 2)

print(" x + 5 =", np.add(x, 5))
print(" x - 5 =", np.subtract(x, 5))
print(" x * 2 =", np.multiply(x, 2))
print(" x / 2 =", np.divide(x, 2))
print(" x ** 2 =", np.power(x, 2))

[0 1 2 3]
 x + 5 = [5 6 7 8]
 x - 5 = [-5 -4 -3 -2]
 x * 2 = [0 2 4 6]
 x / 2 = [0.  0.5 1.  1.5]
 x ** 2 = [0 1 4 9]
 x + 5 = [5 6 7 8]
 x - 5 = [-5 -4 -3 -2]
 x * 2 = [0 2 4 6]
 x / 2 = [0.  0.5 1.  1.5]
 x ** 2 = [0 1 4 9]


In [31]:
# use ufuncs

In [35]:
"""
ufuncs : absolute value
"""

x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [40]:
"""
ufuncs : Trigonmetric functions
np.linspace(start, stop, num) : 선형간격의 벡터생성
"""

theta = np.linspace(0, np.pi, 3)

print(theta)

print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [47]:
"""
ufuncs : Aggregation
"""

x = np.arange(1, 5)
print(x)
aggr = np.add.reduce(x)
print(aggr)
aggr = np.multiply.reduce(x)
print(aggr)

accum = np.add.accumulate(x)
print(accum)

accum = np.multiply.accumulate(x)
print(accum)

[1 2 3 4]
10
24
[ 1  3  6 10]
[ 1  2  6 24]


In [50]:
# Summing the Values in an Array
np.random.seed(3)

arr = np.random.rand(1000000)
print(arr)

print(" sum = ", np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
 sum =  500422.19897015305


In [51]:
%timeit sum(arr) #python style

142 ms ± 5.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [52]:
%timeit np.sum(arr)

1.05 ms ± 44.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [61]:
# other Aggr. funcions

print(arr)
print("max =", np.max(arr))
print("min =", np.min(arr))
print("mean =", np.mean(arr))
print("median =", np.median(arr))
print("percentile =", np.percentile(arr, 90))

print(np.any)

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
max = 0.9999996367889004
min = 1.5496004267534502e-06
mean = 0.500422198970153
median = 0.5005659265960778
percentile = 0.9001765340710965
